# Generated by Django 2.2.28 on 2023-03-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230227_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='was_active_today',
        ),
        migrations.AddField(
            model_name='user',
            name='new_field',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
